sudo: required
services:
  - docker

before_install:
  - docker build -f FranciscoJavierMartin/docker-react Dockerfile.dev .

script:
  - docker run FranciscoJavierMartin/docker-react npm run test -- --coverage