sudo: required
services:
  - docker

before_install:
  - docker build -t FranciscoJavierMartin/docker-react -f Dockerfile.dev .

script:
  - docker run FranciscoJavierMartin/docker-react npm run test -- --coverage